### ISSUE TITLE
Contacts added in module do not show up in table for selecting recipients

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#31]
The Add person feature is not working.

**Comment by ashaban** [comment]
This is fixed @lkwirica can you have a look now!

**Comment by lkwirica** [comment]
Hi, I've just tried it, the record has been saved. How long before the contact is updated in the database? Is it 15 min?

**Comment by cloehr651** [comment]
@ashaban and @lkwirica , is this fixed now?

**Comment by njugunask** [comment]
It now works. I have been able to add myself, searching for the added contact is available when sending messages however in the **search people** it doesn't appear

**Comment by cloehr651** [comment]
Thanks Stanley for the update. @ashaban can you check on why the new contact is not showing up in the search people table?

**Comment by lkwirica** [comment]
I've checked. .this is still outstanding

**Comment by cloehr651** [comment]
@lkwirica can you clarify - when you add a contact the name doesn't show up in the search table or is the issue different now?

**Comment by cloehr651** [comment]
@lkwirica can you please check this whether this issue has been resolved now? If so, you can close it.

**Comment by lkwirica** [comment]
This issue is related to no. #33

**Comment by ashaban** [comment]
@lkwirica please review this together with #33

**Comment by njugunask** [comment]
@Ally, a record added in mHero platform cannot be viewed in the '**search people**' tab.

**Comment by ashaban** [comment]
What is the name you added?

**Comment by njugunask** [comment]
'kungu njuguna' added that either yesterday or the day before

**Comment by ashaban** [comment]
I fixed this issue yesterday, if you are to test it then you need to add a new record.

**Comment by ashaban** [comment]
Kungu Njuguna is there as well, i am not sure how are you searching
![Kungu](https://user-images.githubusercontent.com/3152817/122368883-6438f400-cf66-11eb-9ef3-0b41dc58fbde.png)

**Comment by njugunask** [comment]
If you run a search by two names, there is no available data. That needs to be fixed because of similar 'surnames'

**Comment by ashaban** [comment]
open a new issue please, that is a different issue and should not be tracked on this issue.

**Comment by njugunask** [comment]
I thought it is related because it the search function issue but will open a new one altogether.

**Comment by njugunask** [comment]
This issue has been fixed. Close and move to the done folder.

**Comment by lkwirica** [comment]
@ashaban ,On this issue- Contacts added in module do not show up in table for selecting recipient -issue #31.....I've tried to send a message to Vionora, her name doesn't appear on send messages list.

**Comment by lkwirica** [comment]
> This issue has been fixed. Close and move to the done folder.
Shouldn't be closed, still cannot send message to a contact added.

**Comment by ashaban** [comment]
@lkwirica can you give a name that you added and you can not send a message?

**Comment by ashaban** [comment]
@lkwirica this is working!, can you give the full name of Vionora so that i can track her/him individually

**Comment by lkwirica** [comment]
Atwoli Vionora Kerubo

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/122708982-05c18d80-d266-11eb-9d2c-54a8b406c64c.png)

**Comment by ashaban** [comment]
Vionora was not added to send message page because her/his phone number's country code was missing a plus at the begining, i.e phone number started with 255 instead of +255. I have added a fix for this i.e to accept phone numbers with country code not starting with +. Vionora is now added to the send message page.

**Comment by ashaban** [comment]
@lkwirica Vionora was not added to send message page because her/his phone number's country code was missing a plus at the begining, i.e phone number started with 255 instead of +255. I have added a fix for this i.e to accept phone numbers with country code not starting with +. Vionora is now added to the send message page.

**Comment by njugunask** [comment]
@lkwirica country code should be +254, right? otherwise, the recipient will still not receive any message

**Comment by ashaban** [comment]
@njugunask i meant +254 and not +255

**Comment by njugunask** [comment]
Massive data cleaning of contacts required. Otherwise, the issue should be closed once correction and verification that the recipient can receive messages

**Comment by njugunask** [comment]
@lkwirica, move this closed issue to done folder
